from __future__ import annotations

from collections.abc import Awaitable, Callable

from pydantic import JsonValue

from thoth.domain.operation import OperationRecord
from thoth.ports.operation import OperationReentryAuthorizer
from thoth.protocol.deferred import AcceptedRunning, PendingExecution
from thoth.protocol.jsonrpc import RpcApplicationError, RpcErrorCode

CommandHandler = Callable[
    [dict[str, JsonValue]], Awaitable[dict[str, JsonValue] | AcceptedRunning | PendingExecution]
]

PUBLIC_METHODS: tuple[str, ...] = (
    "revision/timeline/read",
    "revision/restore/apply",
    "revision/timeline/item/read",
    "thread/result/read",
    "thread/result/compare/read",
    "project/review/list",
    "model/settings/read",
    "model/settings/update",
    "model/credential/list",
    "model/credential/register",
    "workspace/setup/read",
    "workspace/setup/update",
    "workspace/ready",
    "field/protocol/seal",
    "field/session/start",
    "field/event/record",
    "field/session/end",
    "field/score/record",
    "field/export/build",
    "projectpack/list",
    "projectpack/run",
    "project/create",
    "project/activate",
    "project/archive",
    "project/delete",
    "project/metadata/update",
    "project/list",
    "project/overlay/update",
    "project/policy/read",
    "project/policy/update",
    "project/read",
    "project/reference/import",
    "project/reference/list",
    "project/role/assign",
    "project/role/list",
    "project/role/revoke",
    "project/cutoff/impact",
    "project/cutoff/update",
    "closure/prepare",
    "closure/read",
    "closure/finalize",
    "closure/list",
    "closure/readiness/read",
    "closure/package/read",
    "closure/openItem/list",
    "closure/reopen/read",
    "closure/retention/read",
    "closure/audit/read",
    "closure/readiness/assess",
    "closure/decide",
    "closure/followup/create",
    "closure/reopen",
    "closure/retention/plan",
    "closure/purge/prepare",
    "export/prepare",
    "export/list",
    "export/read",
    "export/plan/read",
    "export/snapshot/read",
    "export/manifest/read",
    "export/artifact/list",
    "export/verification/read",
    "export/release/read",
    "export/correction/read",
    "export/audit/read",
    "export/plan/create",
    "export/snapshot/create",
    "export/generate",
    "export/verify",
    "export/release/prepare",
    "export/correction/create",
    "project/source/connect",
    "project/source/disconnect",
    "project/source/list",
    "project/source/time/confirm",
    "project/source/time/correct",
    "project/source/scope/read",
    "project/source/scope/grant",
    "project/source/scope/revoke",
    "project/source/scope/assign",
    "project/source/scope/update",
    "thread/start",
    "thread/list",
    "thread/read",
    "thread/activity/list",
    "thread/checkpoint/list",
    "thread/checkpoint/read",
    "thread/input",
    "thread/steer",
    "thread/pause",
    "thread/resume",
    "thread/stop",
    "thread/fork",
    "thread/metadata/update",
    "investigation/read",
    "investigation/list",
    "investigation/audit/read",
    "investigation/start",
    "investigation/update",
    "investigation/pause",
    "investigation/resume",
    "investigation/stop",
    "evidence/list",
    "evidence/read",
    "evidence/packet/read",
    "evidence/conflict/list",
    "evidence/conflict/read",
    "evidence/audit/read",
    "evidence/source/add",
    "evidence/source/refresh",
    "evidence/source/metadata/correct",
    "evidence/span/correct",
    "evidence/link/propose",
    "evidence/link/correct",
    "evidence/challenge",
    "evidence/revalidate",
    "criteria/list",
    "criteria/read",
    "criteria/profile/list",
    "criteria/profile/read",
    "criteria/reference/list",
    "criteria/reference/read",
    "criteria/conflict/list",
    "criteria/conflict/read",
    "criteria/audit/read",
    "criteria/compile",
    "criteria/field/correct",
    "criteria/profile/apply",
    "criteria/revalidate",
    "criteria/recalculate",
    "criteria/reference/generate",
    "criteria/change/propose",
    "object/list",
    "object/read",
    "object/candidate/list",
    "object/candidate/read",
    "object/profile/list",
    "object/profile/read",
    "object/relation/list",
    "object/impact/read",
    "object/attention/list",
    "object/audit/read",
    "object/materialize",
    "object/frame/revise",
    "object/profile/apply",
    "object/facet/update",
    "object/relation/add",
    "object/relation/remove",
    "object/revalidate",
    "object/work/replan",
    "object/split/propose",
    "object/merge/propose",
    "object/attention/acknowledge",
    "object/followup/create",
    "hypothesis/portfolio/read",
    "hypothesis/list",
    "hypothesis/read",
    "hypothesis/graph/read",
    "hypothesis/portfolio/list",
    "hypothesis/relation/list",
    "hypothesis/prediction/list",
    "hypothesis/prediction/read",
    "hypothesis/assumption/list",
    "hypothesis/quality/read",
    "hypothesis/appraisal/read",
    "hypothesis/audit/read",
    "hypothesis/generate",
    "hypothesis/create",
    "hypothesis/revise",
    "hypothesis/intent/update",
    "hypothesis/causal/update",
    "hypothesis/relation/add",
    "hypothesis/relation/remove",
    "hypothesis/assumption/add",
    "hypothesis/prediction/bind",
    "hypothesis/counterevidence/request",
    "hypothesis/portfolio/compose",
    "hypothesis/portfolio/revalidate",
    "hypothesis/test/bind",
    "hypothesis/appraise",
    "hypothesis/split/propose",
    "hypothesis/merge/propose",
    "action/plan/read",
    "action/list",
    "action/read",
    "action/portfolio/list",
    "action/portfolio/read",
    "action/plan/graph",
    "action/step/read",
    "action/impact/read",
    "action/policy/read",
    "action/authorization/read",
    "action/audit/read",
    "action/generate",
    "action/create",
    "action/revise",
    "action/portfolio/compose",
    "action/portfolio/evaluate",
    "action/recommend",
    "action/select",
    "action/plan/compose",
    "action/plan/revise",
    "action/plan/revalidate",
    "action/step/add",
    "action/step/revise",
    "action/impact/recalculate",
    "action/policy/classify",
    "action/authorization/prepare",
    "action/authorization/decide",
    "action/compensation/create",
    "action/merge/propose",
    "execution/list",
    "execution/read",
    "execution/frontier/read",
    "execution/preflight/read",
    "execution/attempt/list",
    "execution/attempt/read",
    "execution/effect/read",
    "execution/reconciliation/read",
    "execution/audit/read",
    "execution/start",
    "execution/pause",
    "execution/resume",
    "execution/cancel",
    "execution/retry",
    "execution/reconcile",
    "execution/observation/link",
    "execution/compensation/propose",
    "execution/invalidate",
    "action/preflight/read",
    "revision/history/read",
    "revision/compare",
    "revision/restore",
    "revision/list",
    "revision/read",
    "revision/content/read",
    "revision/diff/read",
    "revision/graph/read",
    "revision/head/read",
    "revision/changeSet/read",
    "revision/impact/read",
    "revision/conflict/list",
    "revision/conflict/read",
    "revision/restore/preview",
    "revision/baseline/list",
    "revision/baseline/read",
    "revision/audit/read",
    "revision/propose",
    "revision/changeSet/create",
    "revision/changeSet/validate",
    "revision/changeSet/commit",
    "revision/branch/create",
    "revision/merge/propose",
    "revision/merge/resolve",
    "revision/restore/propose",
    "revision/recompute/request",
    "revision/baseline/prepare",
    "revision/baseline/decide",
    "outcome/read",
    "outcome/list",
    "outcome/series/list",
    "outcome/series/read",
    "outcome/profile/list",
    "outcome/profile/read",
    "outcome/attribution/read",
    "outcome/changeSet/read",
    "outcome/impact/read",
    "outcome/audit/read",
    "outcome/series/create",
    "outcome/observation/link",
    "outcome/assess",
    "outcome/reassess",
    "outcome/attribution/assess",
    "outcome/changeSet/propose",
    "outcome/followup/generate",
    "outcome/impact/propose",
    "memory/context/read",
    "memory/list",
    "memory/read",
    "memory/candidate/list",
    "memory/candidate/read",
    "memory/policy/list",
    "memory/policy/read",
    "memory/gate/read",
    "memory/conflict/list",
    "memory/recall/audit",
    "memory/projection/status",
    "memory/candidate/create",
    "memory/candidate/classify",
    "memory/validate",
    "memory/changeSet/propose",
    "memory/revalidate",
    "memory/retire/propose",
    "memory/context/build",
    "memory/projection/rebuild",
    "memory/retention/evaluate",
    "improvement/list",
    "improvement/read",
    "improvement/evaluation/read",
    "improvement/exposure/read",
    "improvement/shadow/read",
    "improvement/canary/read",
    "improvement/promotion/read",
    "improvement/audit/read",
    "improvement/propose",
    "improvement/revise",
    "improvement/evaluation/plan",
    "improvement/evaluation/assess",
    "improvement/evaluation/run",
    "improvement/evaluation/result/read",
    "improvement/exposure/prepare",
    "improvement/exposure/runtime/read",
    "improvement/exposure/start",
    "improvement/exposure/decide",
    "improvement/exposure/complete",
    "improvement/exposure/rollback",
    "improvement/promotion/prepare",
    "improvement/promotion/decide",
    "improvement/rollback/prepare",
    "improvement/retire/propose",
    "receipt/read",
    "receipt/verify",
    "receipt/list",
    "receipt/stream/read",
    "receipt/lineage/read",
    "receipt/bundle/read",
    "receipt/verification/read",
    "receipt/audit/read",
    "receipt/seal",
    "receipt/bundle/create",
    "receipt/bundle/verify",
    "receipt/correction/create",
    "operation/read",
    "operation/checkpoint/read",
    "operation/result/read",
    "operation/pause",
    "operation/cancel",
    "operation/resume",
)

FORBIDDEN_DIRECT_METHODS = frozenset(
    {"setStatus", "approve", "waive", "delete", "forceMerge", "executeR3"}
)


class MethodRegistry:
    def __init__(self) -> None:
        self._handlers: dict[str, CommandHandler] = {}
        self._reentry_authorizers: dict[str, OperationReentryAuthorizer] = {}

    def register_reentry_authorizer(
        self, method: str, authorizer: OperationReentryAuthorizer
    ) -> None:
        self.resolve(method)
        self._reentry_authorizers[method] = authorizer

    def authorize_reentry(self, operation: OperationRecord) -> None:
        authorizer = self._reentry_authorizers.get(operation.method)
        if authorizer is not None:
            authorizer(operation)

    def register(self, method: str, handler: CommandHandler) -> None:
        if method in FORBIDDEN_DIRECT_METHODS:
            raise ValueError(f"direct authority bypass method is prohibited: {method}")
        if method not in PUBLIC_METHODS:
            raise ValueError(f"method is not declared in protocol V0: {method}")
        if method in self._handlers:
            raise ValueError(f"method already registered: {method}")
        self._handlers[method] = handler

    def resolve(self, method: str) -> CommandHandler:
        try:
            return self._handlers[method]
        except KeyError as exc:
            raise RpcApplicationError(
                RpcErrorCode.METHOD_NOT_FOUND,
                f"method is not implemented: {method}",
                data={"method": method},
            ) from exc

    def decorate(self, method: str, decorator: Callable[[CommandHandler], CommandHandler]) -> None:
        self._handlers[method] = decorator(self.resolve(method))

    def registered_methods(self) -> tuple[str, ...]:
        return tuple(sorted(self._handlers))
