"""core ledger

Revision ID: e154fa1aa4eb
Revises:
Create Date: 2026-08-30 06:20:08.468212
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e154fa1aa4eb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_snapshots",
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("content_json", sa.Text(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("content_digest", name="uq_entity_snapshots_content_digest"),
    )
    with op.batch_alter_table("entity_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_snapshots_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entity_snapshots_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entity_snapshots_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("cutoff_at", sa.String(length=32), nullable=False),
        sa.Column("lifecycle", sa.String(length=40), nullable=False),
        sa.Column("policy_ref", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "receipts",
        sa.Column("receipt_id", sa.String(length=160), nullable=False),
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("receipt_type", sa.String(length=40), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("receipt_digest", sa.String(length=64), nullable=False),
        sa.Column("previous_transition_digest", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint("receipt_digest"),
    )
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipts_project_id"), ["project_id"], unique=False)

    op.create_table(
        "structural_nodes",
        sa.Column("node_id", sa.String(length=160), nullable=False),
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("artifact_id", sa.String(length=160), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locator_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("node_id"),
    )
    with op.batch_alter_table("structural_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structural_nodes_artifact_id"), ["artifact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structural_nodes_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "working_heads",
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("aggregate_key", sa.String(length=260), nullable=False),
        sa.Column("revision_digest", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("project_id", "aggregate_key"),
    )
    op.create_table(
        "semantic_revisions",
        sa.Column("revision_id", sa.String(length=160), nullable=False),
        sa.Column("project_id", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=160), nullable=False),
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("actor_json", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_refs_json", sa.Text(), nullable=False),
        sa.Column("affected_refs_json", sa.Text(), nullable=False),
        sa.Column("revision_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["entity_snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("revision_id"),
        sa.UniqueConstraint("revision_digest"),
    )
    with op.batch_alter_table("semantic_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_semantic_revisions_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_semantic_revisions_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_semantic_revisions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "revision_parents",
        sa.Column("revision_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_digest", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["semantic_revisions.revision_id"],
        ),
        sa.PrimaryKeyConstraint("revision_id", "ordinal"),
    )
    op.execute(
        "CREATE VIRTUAL TABLE structural_fts "
        "USING fts5(node_id UNINDEXED, project_id UNINDEXED, "
        "artifact_id UNINDEXED, text)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS structural_fts")
    op.drop_table("revision_parents")
    with op.batch_alter_table("semantic_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semantic_revisions_project_id"))
        batch_op.drop_index(batch_op.f("ix_semantic_revisions_entity_type"))
        batch_op.drop_index(batch_op.f("ix_semantic_revisions_entity_id"))

    op.drop_table("semantic_revisions")
    op.drop_table("working_heads")
    with op.batch_alter_table("structural_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structural_nodes_project_id"))
        batch_op.drop_index(batch_op.f("ix_structural_nodes_artifact_id"))

    op.drop_table("structural_nodes")
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_receipts_project_id"))

    op.drop_table("receipts")
    op.drop_table("projects")
    with op.batch_alter_table("entity_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_snapshots_project_id"))
        batch_op.drop_index(batch_op.f("ix_entity_snapshots_entity_type"))
        batch_op.drop_index(batch_op.f("ix_entity_snapshots_entity_id"))

    op.drop_table("entity_snapshots")
    # ### end Alembic commands ###
