from __future__ import annotations

from typing import Protocol

from thoth.domain.action_full import (
    ActionAuditRecord,
    ActionPlanRecord,
    ActionPortfolioRecord,
    ActionRecord,
    AuthorizationEnvelopeRecord,
)


class ActionStorePort(Protocol):
    def add_action(self, value: ActionRecord) -> None: ...
    def list_actions(self, project_id: str) -> tuple[ActionRecord, ...]: ...
    def read_action(
        self, project_id: str, action_id: str, revision_digest: str | None
    ) -> ActionRecord | None: ...
    def add_portfolio(self, value: ActionPortfolioRecord) -> None: ...
    def list_portfolios(self, project_id: str) -> tuple[ActionPortfolioRecord, ...]: ...
    def read_portfolio(
        self, project_id: str, portfolio_id: str, revision_digest: str | None
    ) -> ActionPortfolioRecord | None: ...
    def add_plan(self, value: ActionPlanRecord) -> None: ...
    def list_plans(self, project_id: str) -> tuple[ActionPlanRecord, ...]: ...
    def read_plan(
        self, project_id: str, plan_id: str, revision_digest: str | None
    ) -> ActionPlanRecord | None: ...
    def add_authorization(self, value: AuthorizationEnvelopeRecord) -> None: ...
    def read_authorization(
        self, project_id: str, authorization_id: str
    ) -> AuthorizationEnvelopeRecord | None: ...
    def list_authorizations(
        self, project_id: str, plan_id: str | None
    ) -> tuple[AuthorizationEnvelopeRecord, ...]: ...
    def append_audit(self, value: ActionAuditRecord) -> None: ...
    def list_audit(
        self, project_id: str, subject_id: str | None
    ) -> tuple[ActionAuditRecord, ...]: ...
