from __future__ import annotations

from typing import Protocol

from thoth.domain.baseline import (
    BaselineCandidate,
    BaselineDecision,
    BaselineSet,
    ProjectHeadSet,
)


class BaselineStorePort(Protocol):
    def put_head_set(self, value: ProjectHeadSet) -> None: ...
    def read_head_set(self, project_id: str) -> ProjectHeadSet | None: ...
    def add_candidate(self, value: BaselineCandidate) -> None: ...
    def read_candidate(self, project_id: str, candidate_id: str) -> BaselineCandidate | None: ...
    def list_candidates(self, project_id: str) -> tuple[BaselineCandidate, ...]: ...
    def list_sets(self, project_id: str) -> tuple[BaselineSet, ...]: ...
    def read_set_by_digest(self, project_id: str, digest: str) -> BaselineSet | None: ...
    def mark_sets_stale(self, project_id: str, baseline_set_ids: tuple[str, ...]) -> None: ...
    def commit_decision(
        self,
        candidate: BaselineCandidate,
        decision: BaselineDecision,
        baseline: BaselineSet | None,
        superseded_ids: tuple[str, ...],
    ) -> None: ...
