from __future__ import annotations

from typing import Protocol

from thoth.domain.criterion_contract import (
    CriterionAuditRecord,
    CriterionConflictRecord,
    CriterionContractRecord,
    CriterionProfileRecord,
    CriterionReferenceCandidate,
)


class CriterionContractStorePort(Protocol):
    def put_profile(self, value: CriterionProfileRecord) -> None: ...
    def list_profiles(self, enabled_only: bool) -> tuple[CriterionProfileRecord, ...]: ...
    def read_profile(
        self, profile_ref: str, version: int | None
    ) -> CriterionProfileRecord | None: ...
    def add_contract(self, value: CriterionContractRecord) -> None: ...
    def list_contracts(self, project_id: str) -> tuple[CriterionContractRecord, ...]: ...
    def read_contract(
        self, project_id: str, criterion_id: str, revision_digest: str | None
    ) -> CriterionContractRecord | None: ...
    def add_reference(self, value: CriterionReferenceCandidate) -> None: ...
    def list_references(
        self, project_id: str, criterion_id: str | None
    ) -> tuple[CriterionReferenceCandidate, ...]: ...
    def read_reference(self, reference_candidate_id: str) -> CriterionReferenceCandidate | None: ...
    def add_conflict(self, value: CriterionConflictRecord) -> None: ...
    def list_conflicts(
        self, project_id: str, criterion_id: str | None
    ) -> tuple[CriterionConflictRecord, ...]: ...
    def read_conflict(self, conflict_id: str) -> CriterionConflictRecord | None: ...
    def append_audit(self, value: CriterionAuditRecord) -> None: ...
    def list_audit(
        self, project_id: str, criterion_id: str
    ) -> tuple[CriterionAuditRecord, ...]: ...
