from __future__ import annotations

from typing import Protocol

from thoth.domain.decision_object_full import (
    DecisionObjectRecord,
    ObjectAttentionRecord,
    ObjectAuditRecord,
    ObjectCandidateRecord,
    ObjectProfileRecord,
    ObjectRelationRecord,
)


class DecisionObjectStorePort(Protocol):
    def put_profile(self, value: ObjectProfileRecord) -> None: ...
    def list_profiles(self, enabled_only: bool) -> tuple[ObjectProfileRecord, ...]: ...
    def read_profile(self, profile_ref: str, version: int | None) -> ObjectProfileRecord | None: ...
    def add_candidate(self, value: ObjectCandidateRecord) -> None: ...
    def list_candidates(
        self, project_id: str, thread_id: str | None
    ) -> tuple[ObjectCandidateRecord, ...]: ...
    def read_candidate(self, candidate_id: str) -> ObjectCandidateRecord | None: ...
    def add_object(self, value: DecisionObjectRecord) -> None: ...
    def list_objects(self, project_id: str) -> tuple[DecisionObjectRecord, ...]: ...
    def read_object(
        self, project_id: str, object_id: str, revision_digest: str | None
    ) -> DecisionObjectRecord | None: ...
    def add_relation(self, value: ObjectRelationRecord) -> None: ...
    def list_relations(
        self, project_id: str, object_id: str
    ) -> tuple[ObjectRelationRecord, ...]: ...
    def read_relation(self, relation_id: str) -> ObjectRelationRecord | None: ...
    def add_attention(self, value: ObjectAttentionRecord) -> None: ...
    def list_attention(
        self, project_id: str, object_id: str | None
    ) -> tuple[ObjectAttentionRecord, ...]: ...
    def read_attention(self, attention_id: str) -> ObjectAttentionRecord | None: ...
    def append_audit(self, value: ObjectAuditRecord) -> None: ...
    def list_audit(self, project_id: str, object_id: str) -> tuple[ObjectAuditRecord, ...]: ...
