from __future__ import annotations

from typing import Protocol

from thoth.domain.evidence_graph import (
    EvidenceAuditRecord,
    EvidenceConflictRecord,
    EvidenceLinkRecord,
    EvidenceSourceRecord,
    ObservationRecord,
    SpanCorrectionRecord,
)


class EvidenceGraphStorePort(Protocol):
    def add_source(self, value: EvidenceSourceRecord) -> None: ...

    def read_source(self, source_id: str) -> EvidenceSourceRecord | None: ...

    def read_source_by_artifact(self, artifact_id: str) -> EvidenceSourceRecord | None: ...

    def list_sources(self, project_id: str) -> tuple[EvidenceSourceRecord, ...]: ...

    def add_observation(self, value: ObservationRecord) -> None: ...

    def read_observation(self, observation_id: str) -> ObservationRecord | None: ...

    def add_link(self, value: EvidenceLinkRecord) -> None: ...

    def read_link(self, evidence_id: str) -> EvidenceLinkRecord | None: ...

    def list_links(
        self, project_id: str, target_id: str | None = None
    ) -> tuple[EvidenceLinkRecord, ...]: ...

    def add_conflict(self, value: EvidenceConflictRecord) -> None: ...

    def read_conflict(self, conflict_id: str) -> EvidenceConflictRecord | None: ...

    def list_conflicts(self, project_id: str) -> tuple[EvidenceConflictRecord, ...]: ...

    def update_conflict(self, value: EvidenceConflictRecord) -> None: ...

    def append_audit(self, value: EvidenceAuditRecord) -> None: ...

    def list_audit(
        self, project_id: str, evidence_ref: str | None, *, offset: int, limit: int
    ) -> tuple[EvidenceAuditRecord, ...]: ...

    def add_span_correction(self, value: SpanCorrectionRecord) -> None: ...

    def list_span_corrections(
        self, project_id: str, span_id: str
    ) -> tuple[SpanCorrectionRecord, ...]: ...
