from __future__ import annotations

from typing import Protocol

from thoth.domain.execution_full import (
    ExecutionAuditRecord,
    ExecutionEffectRecord,
    PlanExecutionRecord,
    ReconciliationRecord,
    StepExecutionAttemptRecord,
)


class ExecutionStorePort(Protocol):
    def add_execution(self, value: PlanExecutionRecord) -> None: ...
    def list_executions(self, project_id: str) -> tuple[PlanExecutionRecord, ...]: ...
    def read_execution(
        self, project_id: str, plan_execution_id: str
    ) -> PlanExecutionRecord | None: ...
    def add_attempt(self, value: StepExecutionAttemptRecord) -> None: ...
    def list_attempts(
        self, project_id: str, plan_execution_id: str
    ) -> tuple[StepExecutionAttemptRecord, ...]: ...
    def read_attempt(
        self, project_id: str, attempt_id: str
    ) -> StepExecutionAttemptRecord | None: ...
    def add_effect(self, value: ExecutionEffectRecord) -> None: ...
    def list_effects(
        self, project_id: str, attempt_id: str
    ) -> tuple[ExecutionEffectRecord, ...]: ...
    def add_reconciliation(self, value: ReconciliationRecord) -> None: ...
    def read_reconciliation(
        self, project_id: str, reconciliation_id: str
    ) -> ReconciliationRecord | None: ...
    def append_audit(self, value: ExecutionAuditRecord) -> None: ...
    def list_audit(
        self, project_id: str, plan_execution_id: str
    ) -> tuple[ExecutionAuditRecord, ...]: ...
