from __future__ import annotations

from typing import Protocol

from thoth.domain.field_measurement import (
    FieldEventRecord,
    FieldExportBundle,
    FieldProtocolSeal,
    FieldScoreRecord,
    FieldSessionMetrics,
    FieldSessionRecord,
)


class FieldMeasurementStorePort(Protocol):
    def put_protocol(self, value: FieldProtocolSeal) -> None: ...
    def read_protocol(self, project_id: str, digest: str) -> FieldProtocolSeal | None: ...
    def list_protocols(self, project_id: str) -> tuple[FieldProtocolSeal, ...]: ...
    def put_session(self, value: FieldSessionRecord) -> None: ...
    def read_session(self, project_id: str, session_id: str) -> FieldSessionRecord | None: ...
    def list_sessions(
        self, project_id: str, protocol_digest: str
    ) -> tuple[FieldSessionRecord, ...]: ...
    def put_event(self, value: FieldEventRecord) -> None: ...
    def list_events(
        self, project_id: str, session_id: str | None = None
    ) -> tuple[FieldEventRecord, ...]: ...
    def put_metrics(self, value: FieldSessionMetrics, project_id: str) -> None: ...
    def list_metrics(self, project_id: str) -> tuple[FieldSessionMetrics, ...]: ...
    def put_score(self, value: FieldScoreRecord) -> None: ...
    def list_scores(self, project_id: str) -> tuple[FieldScoreRecord, ...]: ...
    def put_export(self, value: FieldExportBundle) -> None: ...


class FieldMeasurementObserverPort(Protocol):
    def validate_session(self, *, project_id: str, session_id: str) -> None: ...

    def record_rpc_event(
        self,
        *,
        project_id: str,
        session_id: str,
        method: str,
        outcome: str,
    ) -> None: ...
