from __future__ import annotations

from typing import Protocol

from thoth.domain.hypothesis_full import (
    AuxiliaryAssumptionRecord,
    HypothesisAppraisalRecord,
    HypothesisAuditRecord,
    HypothesisPortfolioRecord,
    HypothesisRecord,
    HypothesisRelationRecord,
    HypothesisTestBinding,
    PredictionRecord,
)


class HypothesisStorePort(Protocol):
    def add_hypothesis(self, value: HypothesisRecord) -> None: ...
    def list_hypotheses(self, project_id: str) -> tuple[HypothesisRecord, ...]: ...
    def read_hypothesis(
        self, project_id: str, hypothesis_id: str, revision_digest: str | None
    ) -> HypothesisRecord | None: ...
    def add_portfolio(self, value: HypothesisPortfolioRecord) -> None: ...
    def list_portfolios(self, project_id: str) -> tuple[HypothesisPortfolioRecord, ...]: ...
    def read_portfolio(
        self, project_id: str, portfolio_id: str, revision_digest: str | None
    ) -> HypothesisPortfolioRecord | None: ...
    def add_relation(self, value: HypothesisRelationRecord) -> None: ...
    def list_relations(
        self, project_id: str, portfolio_id: str | None
    ) -> tuple[HypothesisRelationRecord, ...]: ...
    def read_relation(self, relation_id: str) -> HypothesisRelationRecord | None: ...
    def add_assumption(self, value: AuxiliaryAssumptionRecord) -> None: ...
    def list_assumptions(
        self, project_id: str, hypothesis_id: str | None
    ) -> tuple[AuxiliaryAssumptionRecord, ...]: ...
    def add_prediction(self, value: PredictionRecord) -> None: ...
    def list_predictions(
        self, project_id: str, hypothesis_id: str | None
    ) -> tuple[PredictionRecord, ...]: ...
    def read_prediction(self, prediction_id: str) -> PredictionRecord | None: ...
    def add_test_binding(self, value: HypothesisTestBinding) -> None: ...
    def list_test_bindings(
        self, project_id: str, prediction_id: str | None
    ) -> tuple[HypothesisTestBinding, ...]: ...
    def add_appraisal(self, value: HypothesisAppraisalRecord) -> None: ...
    def list_appraisals(
        self, project_id: str, hypothesis_id: str
    ) -> tuple[HypothesisAppraisalRecord, ...]: ...
    def append_audit(self, value: HypothesisAuditRecord) -> None: ...
    def list_audit(
        self, project_id: str, hypothesis_id: str
    ) -> tuple[HypothesisAuditRecord, ...]: ...
