from __future__ import annotations

from typing import Protocol

from thoth.domain.outcome_full import (
    AttributionAssessmentRecord,
    OutcomeAssessmentRecord,
    OutcomeAuditRecord,
    OutcomeChangeSetRecord,
    OutcomeImpactRecord,
    OutcomeProfileRecord,
    OutcomeSeriesRecord,
)


class OutcomeStorePort(Protocol):
    def put_profile(self, value: OutcomeProfileRecord) -> None: ...
    def list_profiles(self, enabled_only: bool) -> tuple[OutcomeProfileRecord, ...]: ...
    def read_profile(
        self, profile_ref: str, version: int | None
    ) -> OutcomeProfileRecord | None: ...
    def add_series(self, value: OutcomeSeriesRecord) -> None: ...
    def list_series(self, project_id: str) -> tuple[OutcomeSeriesRecord, ...]: ...
    def read_series(
        self, project_id: str, series_id: str, revision_digest: str | None
    ) -> OutcomeSeriesRecord | None: ...
    def add_assessment(self, value: OutcomeAssessmentRecord) -> None: ...
    def list_assessments(self, project_id: str) -> tuple[OutcomeAssessmentRecord, ...]: ...
    def read_assessment(
        self, project_id: str, assessment_id: str, revision_digest: str | None
    ) -> OutcomeAssessmentRecord | None: ...
    def add_attribution(self, value: AttributionAssessmentRecord) -> None: ...
    def read_attribution(
        self, project_id: str, attribution_id: str
    ) -> AttributionAssessmentRecord | None: ...
    def add_change_set(self, value: OutcomeChangeSetRecord) -> None: ...
    def read_change_set(
        self, project_id: str, change_set_id: str
    ) -> OutcomeChangeSetRecord | None: ...
    def add_impact(self, value: OutcomeImpactRecord) -> None: ...
    def read_impact(self, project_id: str, impact_id: str) -> OutcomeImpactRecord | None: ...
    def append_audit(self, value: OutcomeAuditRecord) -> None: ...
    def list_audit(
        self, project_id: str, subject_id: str | None
    ) -> tuple[OutcomeAuditRecord, ...]: ...
