from __future__ import annotations

from typing import Protocol

from thoth.domain.receipt_dag import (
    ReceiptBundle,
    ReceiptDagEdge,
    ReceiptDagManifest,
    ReceiptDagNode,
    ReceiptDagVerification,
)


class ReceiptDagStorePort(Protocol):
    def put_node(self, value: ReceiptDagNode) -> None: ...
    def put_edge(self, value: ReceiptDagEdge) -> None: ...
    def list_nodes(self, project_id: str) -> tuple[ReceiptDagNode, ...]: ...
    def list_edges(self, project_id: str) -> tuple[ReceiptDagEdge, ...]: ...
    def put_manifest(self, value: ReceiptDagManifest) -> None: ...
    def read_manifest(self, project_id: str) -> ReceiptDagManifest | None: ...
    def put_bundle(self, value: ReceiptBundle) -> None: ...
    def read_bundle(self, project_id: str, bundle_id: str) -> ReceiptBundle | None: ...
    def put_verification(self, value: ReceiptDagVerification) -> None: ...
    def list_verifications(
        self, project_id: str, subject_id: str | None = None
    ) -> tuple[ReceiptDagVerification, ...]: ...
