from __future__ import annotations

from typing import Protocol, runtime_checkable

from thoth.domain.operation import OperationRecord
from thoth.domain.resource_scope import (
    ResourceIntakeBasis,
    ResourceScopeReceipt,
    ResourceScopeRecord,
    ResourceScopeTemplate,
    StagedResourceScope,
)


class ResourceScopeStorePort(Protocol):
    def read(self, project_id: str, resource_ref: str) -> ResourceScopeRecord | None: ...
    def history(self, project_id: str, resource_ref: str) -> tuple[ResourceScopeRecord, ...]: ...
    def append(
        self, value: ResourceScopeRecord, receipt: ResourceScopeReceipt, *, expected_revision: int
    ) -> None: ...


class ResourceScopeAdmissionPort(Protocol):
    def prepare_derived_intake(
        self, project_id: str, parent_refs: tuple[str, ...]
    ) -> ResourceIntakeBasis: ...
    def prepare_intake(
        self, project_id: str, template: ResourceScopeTemplate | None = None
    ) -> ResourceIntakeBasis: ...
    def stage(
        self, resource_ref: str, basis: ResourceIntakeBasis, *, derived: bool = False
    ) -> StagedResourceScope: ...
    def admit(self, value: StagedResourceScope | None) -> None: ...
    def ensure_derived(
        self, project_id: str, resource_ref: str, parent_refs: tuple[str, ...], *, is_new: bool
    ) -> ResourceScopeRecord: ...


class ResourceAccessPort(Protocol):
    def require_read(self, project_id: str, resource_ref: str) -> None: ...
    def require_reads(self, project_id: str, resource_refs: tuple[str, ...]) -> None: ...
    def may_read(self, project_id: str, resource_ref: str) -> bool: ...
    def require_operation(self, operation: OperationRecord) -> None: ...
    def require_revision(self, project_id: str, revision_digest: str) -> None: ...
    def require_admitted_revision(self, project_id: str, revision_digest: str) -> None: ...
    def may_read_revision(self, project_id: str, revision_digest: str) -> bool: ...


@runtime_checkable
class HistoricalOperationVerifierPort(Protocol):
    def verify_historical_operation_access(self, operation: OperationRecord) -> None: ...


class ResourceRecordAccessPort(ResourceAccessPort, Protocol):
    def record_control_lineage(
        self, project_id: str, digest: str, parents: tuple[str, ...]
    ) -> None: ...


class ResourceWriteAccessPort(ResourceAccessPort, Protocol):
    def require_write(self, project_id: str, resource_ref: str) -> None: ...
    def may_write(self, project_id: str, resource_ref: str) -> bool: ...
