from typing import Protocol


class WorkerIdentityPort(Protocol):
    @property
    def worker_id(self) -> str: ...
    @property
    def process_id(self) -> int: ...
    @property
    def process_marker(self) -> str: ...
    def is_alive(self, process_id: int, process_marker: str, worker_id: str) -> bool | None: ...
    def close(self) -> None: ...
