from __future__ import annotations

from enum import StrEnum


class EntityType(StrEnum):
    PROJECT = "PROJECT"
    THREAD = "THREAD"
    DECISION_OBJECT = "DECISION_OBJECT"
    ARTIFACT = "ARTIFACT"
    EVIDENCE = "EVIDENCE"
    CRITERION = "CRITERION"
    HYPOTHESIS = "HYPOTHESIS"
    ACTION = "ACTION"
    EXECUTION = "EXECUTION"
    OUTCOME = "OUTCOME"
    MEMORY = "MEMORY"
    CLOSURE = "CLOSURE"
    EXPORT = "EXPORT"


class SecurityClass(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class AuthorityState(StrEnum):
    UNCLASSIFIED = "UNCLASSIFIED"
    INFORMAL = "INFORMAL"
    OFFICIAL = "OFFICIAL"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    NOT_ADMISSIBLE = "NOT_ADMISSIBLE"


class CutoffState(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    AFTER_CUTOFF = "AFTER_CUTOFF"
    UNKNOWN_TIME = "UNKNOWN_TIME"
    PROHIBITED_CONTEXT = "PROHIBITED_CONTEXT"


class SupportState(StrEnum):
    DISCOVERED = "DISCOVERED"
    EXTRACTED = "EXTRACTED"
    SUPPORTED_CANDIDATE = "SUPPORTED_CANDIDATE"
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    REFUTED = "REFUTED"
    UNRESOLVED = "UNRESOLVED"


class VerificationState(StrEnum):
    NOT_CHECKED = "NOT_CHECKED"
    SCHEMA_VALID = "SCHEMA_VALID"
    PROVENANCE_VALID = "PROVENANCE_VALID"
    DETERMINISTICALLY_VERIFIED = "DETERMINISTICALLY_VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"


class ProjectLifecycle(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSING = "CLOSING"
    ARCHIVED_READ_ONLY = "ARCHIVED_READ_ONLY"


class OperationState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ModelRole(StrEnum):
    RESEARCH_PLANNER = "RESEARCH_PLANNER"
    EVIDENCE_RERANKER = "EVIDENCE_RERANKER"
    SEMANTIC_REVIEWER = "SEMANTIC_REVIEWER"
    REVIEW_ADJUDICATOR = "REVIEW_ADJUDICATOR"
    SOURCE_PLANNER = "SOURCE_PLANNER"
    HYPOTHESIS_REVIEWER = "HYPOTHESIS_REVIEWER"
    EVIDENCE_EXTRACTOR = "EVIDENCE_EXTRACTOR"
    SUFFICIENCY_EXPLAINER = "SUFFICIENCY_EXPLAINER"
    HYPOTHESIS_GENERATOR = "HYPOTHESIS_GENERATOR"
    COUNTEREVIDENCE_CHALLENGER = "COUNTEREVIDENCE_CHALLENGER"
    ACTION_PLANNER = "ACTION_PLANNER"
    USER_EXPLAINER = "USER_EXPLAINER"
    REFERENCE_MAPPER = "REFERENCE_MAPPER"


class ImpactStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    INVALIDATED = "INVALIDATED"
    RECALCULATION_REQUIRED = "RECALCULATION_REQUIRED"


class MemoryPayloadMode(StrEnum):
    DOMAIN_REFERENCE = "DOMAIN_REFERENCE"
    MEMORY_ASSERTION = "MEMORY_ASSERTION"


class MemoryKind(StrEnum):
    FACT = "FACT"
    FAILURE = "FAILURE"
    REFERENCE = "REFERENCE"
    HYPOTHESIS = "HYPOTHESIS"
    DECISION = "DECISION"
    ACTION = "ACTION"
    LESSON = "LESSON"


class RecallEligibility(StrEnum):
    EXCLUDED = "EXCLUDED"
    AUDIT_ONLY = "AUDIT_ONLY"
    EVIDENCE_SEARCH_ONLY = "EVIDENCE_SEARCH_ONLY"
    WORKING_CONTEXT = "WORKING_CONTEXT"
    ACTION_CONTEXT = "ACTION_CONTEXT"


class MemoryLifecycle(StrEnum):
    CURRENT = "CURRENT"
    SUPERSEDED = "SUPERSEDED"
    RETIRED = "RETIRED"


class EvidenceEffect(StrEnum):
    SUPPORT = "SUPPORT"
    COUNTER = "COUNTER"
    NEUTRAL = "NEUTRAL"


class OutcomeStatus(StrEnum):
    OBSERVED = "OBSERVED"
    PARTIAL = "PARTIAL"
    INCONCLUSIVE = "INCONCLUSIVE"
    INVALIDATED = "INVALIDATED"


class CriterionOrigin(StrEnum):
    DOCUMENT_EXTRACTED = "DOCUMENT_EXTRACTED"
    REFERENCE_PROPOSAL = "REFERENCE_PROPOSAL"


class CriterionCompilationStatus(StrEnum):
    EVALUATOR_READY = "EVALUATOR_READY"
    EXPERT_REVIEW_REQUIRED = "EXPERT_REVIEW_REQUIRED"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    REJECTED = "REJECTED"


class ActionCompilationStatus(StrEnum):
    AUTO_CANDIDATE = "AUTO_CANDIDATE"
    PROTECTED_ACTION = "PROTECTED_ACTION"
    PROHIBITED = "PROHIBITED"
    REJECTED = "REJECTED"


class ActionPlanCompilationStatus(StrEnum):
    READY = "READY"
    HOLD = "HOLD"


class DecisionObjectLifecycle(StrEnum):
    OPEN = "OPEN"
    HELD = "HELD"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ResolutionState(StrEnum):
    UNRESOLVED = "UNRESOLVED"
    PARTIAL = "PARTIAL"
    RESOLVED = "RESOLVED"
    ABSTAINED = "ABSTAINED"


class ExecutionAttemptState(StrEnum):
    PREPARED = "PREPARED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    CANCELLED = "CANCELLED"
    UNKNOWN_COMPLETION = "UNKNOWN_COMPLETION"


class OutcomeValidity(StrEnum):
    NOT_ASSESSED = "NOT_ASSESSED"
    VALID = "VALID"
    INVALID = "INVALID"
    INCONCLUSIVE = "INCONCLUSIVE"


class ClosureStatus(StrEnum):
    OPEN = "OPEN"
    READY = "READY"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"


class ExportReleaseState(StrEnum):
    LOCAL_DRAFT = "LOCAL_DRAFT"
    LOCAL_SEALED = "LOCAL_SEALED"
    RELEASE_PREPARED = "RELEASE_PREPARED"
    EXTERNALLY_RELEASED = "EXTERNALLY_RELEASED"


class EffectObservation(StrEnum):
    CONFIRMED = "CONFIRMED"
    ABSENT = "ABSENT"
    UNKNOWN = "UNKNOWN"


class ThreadLifecycle(StrEnum):
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    RESOLVED = "RESOLVED"
    ABSTAINED = "ABSTAINED"
    HANDED_OFF = "HANDED_OFF"
    STOPPED = "STOPPED"


class ThreadExecutionState(StrEnum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    PAUSE_PENDING = "PAUSE_PENDING"
    PAUSED = "PAUSED"
    WAITING_INPUT = "WAITING_INPUT"
    WAITING_PROTECTED_ACTION = "WAITING_PROTECTED_ACTION"
    CANCELING = "CANCELING"


class StructuralNodeKind(StrEnum):
    SECTION = "SECTION"
    PARAGRAPH = "PARAGRAPH"
    TABLE = "TABLE"
    ROW = "ROW"
    CELL = "CELL"
    CAPTION = "CAPTION"
    HEADER = "HEADER"
    UNIT = "UNIT"
    FOOTNOTE = "FOOTNOTE"
    MENTION = "MENTION"
    ATTACHMENT = "ATTACHMENT"
    UNSUPPORTED_ELEMENT = "UNSUPPORTED_ELEMENT"


class ParserErrorCode(StrEnum):
    AMBIGUOUS_PARSER_SELECTION = "AMBIGUOUS_PARSER_SELECTION"
    PARSER_CAPABILITY_UNAVAILABLE = "PARSER_CAPABILITY_UNAVAILABLE"
    PARSER_DEADLINE = "PARSER_DEADLINE"
    BYTE_HASH_MISMATCH = "BYTE_HASH_MISMATCH"
    CORRUPT_DOCUMENT = "CORRUPT_DOCUMENT"
    DIRTY_GIT_TARGET = "DIRTY_GIT_TARGET"
    ENCRYPTED_DOCUMENT = "ENCRYPTED_DOCUMENT"
    EXTERNAL_LINK_IGNORED = "EXTERNAL_LINK_IGNORED"
    FORMULA_NOT_RECALCULATED = "FORMULA_NOT_RECALCULATED"
    HIDDEN_CONTENT = "HIDDEN_CONTENT"
    MEDIA_TYPE_MISMATCH = "MEDIA_TYPE_MISMATCH"
    OCR_REQUIRED = "OCR_REQUIRED"
    OVERSIZED_ARCHIVE = "OVERSIZED_ARCHIVE"
    PARTIAL_EXTRACTION = "PARTIAL_EXTRACTION"
    UNSUPPORTED_ELEMENT = "UNSUPPORTED_ELEMENT"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    UNTRUSTED_LOG_LINE = "UNTRUSTED_LOG_LINE"
    ZIP_SLIP = "ZIP_SLIP"


class DimensionStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class SufficiencyStatus(StrEnum):
    READY_FOR_MECHANICAL_EVALUATION = "READY_FOR_MECHANICAL_EVALUATION"
    READY_TO_GENERATE_HYPOTHESES = "READY_TO_GENERATE_HYPOTHESES"
    EVIDENCE_ACQUISITION_REQUIRED = "EVIDENCE_ACQUISITION_REQUIRED"
    EXPERT_INPUT_REQUIRED = "EXPERT_INPUT_REQUIRED"
    INCOMPARABLE = "INCOMPARABLE"
    ABSTAIN = "ABSTAIN"


class CausalLocus(StrEnum):
    INPUT_MATERIAL_DATA = "INPUT_MATERIAL_DATA"
    MEASUREMENT_OBSERVATION = "MEASUREMENT_OBSERVATION"
    METHOD_DESIGN_IMPLEMENTATION = "METHOD_DESIGN_IMPLEMENTATION"
    COMPONENT_INTERFACE_SYSTEM = "COMPONENT_INTERFACE_SYSTEM"
    ENVIRONMENT_CONTEXT = "ENVIRONMENT_CONTEXT"
    HUMAN_ORGANIZATION_EXECUTION = "HUMAN_ORGANIZATION_EXECUTION"
    OTHER_WITH_DESCRIPTION = "OTHER_WITH_DESCRIPTION"


class CausalDepth(StrEnum):
    PROXIMATE = "PROXIMATE"
    INTERMEDIATE = "INTERMEDIATE"
    SYSTEMIC = "SYSTEMIC"
    UNDETERMINED = "UNDETERMINED"


class HypothesisStatus(StrEnum):
    DRAFT = "DRAFT"
    GROUNDED_CANDIDATE = "GROUNDED_CANDIDATE"
    COUNTEREVIDENCE_CHECKED = "COUNTEREVIDENCE_CHECKED"
    PREDICTION_BOUND = "PREDICTION_BOUND"
    TESTABLE = "TESTABLE"
    EMPIRICALLY_UPDATED = "EMPIRICALLY_UPDATED"
    INCONCLUSIVE = "INCONCLUSIVE"
    ELIMINATED_WITHIN_SCOPE = "ELIMINATED_WITHIN_SCOPE"


class PortfolioStatus(StrEnum):
    DRAFT = "DRAFT"
    GROUNDED = "GROUNDED"
    TESTABLE = "TESTABLE"
    EMPIRICALLY_UPDATED = "EMPIRICALLY_UPDATED"


class RiskTier(StrEnum):
    R0 = "R0"
    R1 = "R1"
    R2 = "R2"
    R3 = "R3"
    R4 = "R4"


class ExecutionAuthority(StrEnum):
    AUTO_R0 = "AUTO_R0"
    PREAUTHORIZED_R1 = "PREAUTHORIZED_R1"
    SANDBOX_ONLY_R2 = "SANDBOX_ONLY_R2"
    HUMAN_REQUIRED_R3 = "HUMAN_REQUIRED_R3"
    PROHIBITED_R4 = "PROHIBITED_R4"


class ActionState(StrEnum):
    PROPOSED = "PROPOSED"
    RISK_CLASSIFIED = "RISK_CLASSIFIED"
    AUTO_ALLOWED = "AUTO_ALLOWED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    INVALIDATED = "INVALIDATED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    PROHIBITED = "PROHIBITED"


class Reversibility(StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"
    NONE = "NONE"


class ReceiptType(StrEnum):
    TRANSITION = "TRANSITION"
    AUTHORIZATION = "AUTHORIZATION"
    EXECUTION = "EXECUTION"
    OUTCOME = "OUTCOME"
    MEMORY = "MEMORY"
    IMPROVEMENT = "IMPROVEMENT"
    CLOSURE = "CLOSURE"
    EXPORT = "EXPORT"


class ReceiptClaimScope(StrEnum):
    TRANSITION_RECORDED = "TRANSITION_RECORDED"
    ARTIFACT_INTEGRITY = "ARTIFACT_INTEGRITY"
    PROVENANCE_BOUND = "PROVENANCE_BOUND"
    AUTHORIZATION_RECORDED = "AUTHORIZATION_RECORDED"
    EXECUTION_RECORDED = "EXECUTION_RECORDED"
    OUTCOME_ASSESSMENT_RECORDED = "OUTCOME_ASSESSMENT_RECORDED"
    CLOSURE_DECISION_RECORDED = "CLOSURE_DECISION_RECORDED"
    EXPORT_SNAPSHOT_RECORDED = "EXPORT_SNAPSHOT_RECORDED"


class IntegrityState(StrEnum):
    NOT_CHECKED = "NOT_CHECKED"
    VALID = "VALID"
    INVALID = "INVALID"


class ProvenanceState(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"


class SignatureState(StrEnum):
    NOT_PRESENT = "NOT_PRESENT"
    VALID = "VALID"
    INVALID = "INVALID"
    UNKNOWN_SIGNER = "UNKNOWN_SIGNER"


class TimestampTrust(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"
    SIGNED_ATTESTATION = "SIGNED_ATTESTATION"
    TSA_VERIFIED = "TSA_VERIFIED"
    INVALID = "INVALID"


class ActorKind(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    TOOL = "TOOL"
    SYSTEM = "SYSTEM"
